name: Validación de seguridad Titvo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  titvo-security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Escaneo de seguridad Titvo
        uses: KaribuLab/titvo-security-scan-action@main
        with:
          titvo_api_endpoint: ${{ vars.TITVO_API_ENDPOINT }}
          titvo_api_key: ${{ secrets.TITVO_API_KEY }}
          github_token: ${{ github.token }}
          github_repo_name: ${{ github.repository }}
          github_commit_sha: ${{ github.sha }}
          github_assignee: ${{ github.actor }}
